/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZahtjevRouteImport } from './routes/zahtjev'
import { Route as KorisnickiPodaciRouteImport } from './routes/korisnicki-podaci'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AnketaRouteImport } from './routes/anketa'
import { Route as IndexRouteImport } from './routes/index'

const ZahtjevRoute = ZahtjevRouteImport.update({
  id: '/zahtjev',
  path: '/zahtjev',
  getParentRoute: () => rootRouteImport,
} as any)
const KorisnickiPodaciRoute = KorisnickiPodaciRouteImport.update({
  id: '/korisnicki-podaci',
  path: '/korisnicki-podaci',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AnketaRoute = AnketaRouteImport.update({
  id: '/anketa',
  path: '/anketa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anketa': typeof AnketaRoute
  '/kontakt': typeof KontaktRoute
  '/korisnicki-podaci': typeof KorisnickiPodaciRoute
  '/zahtjev': typeof ZahtjevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anketa': typeof AnketaRoute
  '/kontakt': typeof KontaktRoute
  '/korisnicki-podaci': typeof KorisnickiPodaciRoute
  '/zahtjev': typeof ZahtjevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anketa': typeof AnketaRoute
  '/kontakt': typeof KontaktRoute
  '/korisnicki-podaci': typeof KorisnickiPodaciRoute
  '/zahtjev': typeof ZahtjevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anketa' | '/kontakt' | '/korisnicki-podaci' | '/zahtjev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anketa' | '/kontakt' | '/korisnicki-podaci' | '/zahtjev'
  id:
    | '__root__'
    | '/'
    | '/anketa'
    | '/kontakt'
    | '/korisnicki-podaci'
    | '/zahtjev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnketaRoute: typeof AnketaRoute
  KontaktRoute: typeof KontaktRoute
  KorisnickiPodaciRoute: typeof KorisnickiPodaciRoute
  ZahtjevRoute: typeof ZahtjevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zahtjev': {
      id: '/zahtjev'
      path: '/zahtjev'
      fullPath: '/zahtjev'
      preLoaderRoute: typeof ZahtjevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korisnicki-podaci': {
      id: '/korisnicki-podaci'
      path: '/korisnicki-podaci'
      fullPath: '/korisnicki-podaci'
      preLoaderRoute: typeof KorisnickiPodaciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anketa': {
      id: '/anketa'
      path: '/anketa'
      fullPath: '/anketa'
      preLoaderRoute: typeof AnketaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnketaRoute: AnketaRoute,
  KontaktRoute: KontaktRoute,
  KorisnickiPodaciRoute: KorisnickiPodaciRoute,
  ZahtjevRoute: ZahtjevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
